const testimonials = [
    {
        id: 1,
        name: "Ravi Mehra",
        company: "Patient",
        content: "Dr. Manas Agrawal's expertise in cardiology saved my life. His diagnosis was quick, and the treatment was effective. I'm now healthier than ever.",
        service: "Cardiology Consultation",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 2,
        name: "Priya Nair",
        company: "Patient",
        content: "I was nervous about my surgery, but Dr. Agrawal made me feel comfortable and confident. His care throughout my recovery was outstanding.",
        service: "Surgical Procedure",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 3,
        name: "Anil Sharma",
        company: "Patient",
        content: "I visited Dr. Manas Agrawal for my heart condition, and his treatment plan has been a game-changer. His professionalism and care are unmatched.",
        service: "Cardiology Treatment",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 4,
        name: "Sneha Gupta",
        company: "Patient",
        content: "Dr. Agrawal is not only an exceptional cardiologist but also a great listener. He took the time to explain my condition in detail and provided compassionate care.",
        service: "Cardiology Consultation",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 5,
        name: "Rohit Patel",
        company: "Patient",
        content: "My experience with Dr. Manas Agrawal was wonderful. His approach to treating my high blood pressure was thoughtful, and the results have been amazing.",
        service: "Hypertension Management",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 6,
        name: "Nisha Verma",
        company: "Patient",
        content: "Dr. Agrawal's expertise in preventive cardiology helped me avoid major health issues. I'm grateful for his proactive care and guidance.",
        service: "Preventive Cardiology",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 7,
        name: "Amit Chawla",
        company: "Patient",
        content: "The entire experience with Dr. Manas Agrawal was excellent. He and his team were professional, and my treatment went smoothly from start to finish.",
        service: "Cardiology Treatment",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 8,
        name: "Meena Joshi",
        company: "Patient",
        content: "Dr. Agrawal provided me with outstanding care during my heart surgery. He was attentive and ensured I understood every step of the process.",
        service: "Heart Surgery",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 9,
        name: "Suresh Gupta",
        company: "Patient",
        content: "I can't thank Dr. Agrawal enough for his exceptional care during my heart attack recovery. He gave me a new lease on life, and I'm eternally grateful.",
        service: "Heart Attack Recovery",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 10,
        name: "Pooja Agarwal",
        company: "Patient",
        content: "Dr. Agrawal was incredible throughout my treatment. He listened to all my concerns and provided a tailored plan that has greatly improved my heart health.",
        service: "Heart Health Management",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 11,
        name: "Vikram Rao",
        company: "Patient",
        content: "Dr. Agrawal’s preventive care helped me avoid serious heart issues. His dedication to patient care is truly commendable.",
        service: "Preventive Cardiology",
        image: "https://via.placeholder.com/150",
    },
    {
        id: 12,
        name: "Sonia Desai",
        company: "Patient",
        content: "Thanks to Dr. Agrawal, my cholesterol is now under control. His attention to detail and patient-first approach made all the difference.",
        service: "Cholesterol Management",
        image: "https://via.placeholder.com/150",
    },
];

export default testimonials;
